plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

plugins:
  - jekyll-include-cache
  - gemfile

#theme: jekyll-theme-minima
remote_theme: rundocs/jekyll-rtd-theme


#remote_theme: pages-themes/minimal@v0.2.0
